<?php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_6070194424493',
	'title' => 'Popup Settings',
	'fields' => array(
		array(
			'key' => 'field_60701a5b09c77',
			'label' => 'General Settings',
			'name' => '',
			'type' => 'accordion',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'open' => 1,
			'multi_expand' => 1,
			'endpoint' => 0,
		),
		array(
			'key' => 'field_6070194e09c75',
			'label' => 'Where to show this popup?',
			'name' => 'nine3_popup_select_where',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'All Pages' => 'All Pages',
				'Select Page' => 'Select Page',
				'Custom URL' => 'Custom URL',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => 'All Pages',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_607019fc09c76',
			'label' => 'Page selector',
			'name' => 'nine3_popup_page_selector',
			'type' => 'relationship',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_6070194e09c75',
						'operator' => '==',
						'value' => 'Select Page',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => '',
			'taxonomy' => '',
			'filters' => array(
				0 => 'search',
				1 => 'post_type',
				2 => 'taxonomy',
			),
			'elements' => '',
			'min' => '',
			'max' => '',
			'return_format' => 'id',
		),
		array(
			'key' => 'field_60701b260bd9b',
			'label' => 'Custom URL',
			'name' => 'nine3_popup_custom_url',
			'type' => 'textarea',
			'instructions' => 'If you can\'t find the website page in the Page selector add the full URLs here, 1 URL on each line.',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_6070194e09c75',
						'operator' => '==',
						'value' => 'Custom URL',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_6103c03a6d675',
			'label' => 'Time Delay',
			'name' => 'nine3_popup_delay',
			'type' => 'number',
			'instructions' => 'Set a time delay (in seconds) before the popup appears.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => 0,
			'max' => '',
			'step' => '',
		),
		array(
			'key' => 'field_60740b0564bd8',
			'label' => 'Cookie Expiry',
			'name' => 'nine3_popup_cookie_expiry',
			'type' => 'text',
			'instructions' => 'A cookie is set in the browser when the popup is closed. Enter in plain text how long to wait before the popup reappears (eg: 1 day).',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '1 day',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_60741c7f59f22',
			'label' => 'Priority',
			'name' => 'nine3_popup_priority',
			'type' => 'number',
			'instructions' => 'If there are multiple popups this controls the order they appear in. The higher the number the higher the priority.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => 0,
			'max' => '',
			'step' => '',
		),
		array(
			'key' => 'field_6073ffa0312eb',
			'label' => 'Display Settings',
			'name' => '',
			'type' => 'accordion',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'open' => 1,
			'multi_expand' => 1,
			'endpoint' => 0,
		),
		array(
			'key' => 'field_607402df312ec',
			'label' => 'Position',
			'name' => 'nine3_popup_position',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'left top' => 'Top Left',
				'center top' => 'Top Center',
				'right top' => 'Top Right',
				'left center' => 'Middle Left',
				'center' => 'Middle Center',
				'right center' => 'Middle Right',
				'left bottom' => 'Bottom Left',
				'center bottom' => 'Bottom Center',
				'right bottom' => 'Bottom Right',
			),
			'default_value' => 'center',
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_6074069bfed11',
			'label' => 'Size',
			'name' => 'nine3_popup_size',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'table',
			'sub_fields' => array(
				array(
					'key' => 'field_607406adfed12',
					'label' => 'Width',
					'name' => 'width',
					'type' => 'number',
					'instructions' => 'Percentage of screen width covered',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 90,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => '',
					'max' => '',
					'step' => '',
				),
				array(
					'key' => 'field_607406c9fed13',
					'label' => 'Height',
					'name' => 'height',
					'type' => 'number',
					'instructions' => 'Percentage of screen height covered',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 90,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => '',
					'max' => '',
					'step' => '',
				),
			),
		),
		array(
			'key' => 'field_607406f2fed14',
			'label' => 'Animation',
			'name' => 'nine3_popup_animation',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'default' => 'Default',
				'fade' => 'Fade',
				'slide' => 'Slide',
				'fade_slide' => 'Fade/Slide',
			),
			'default_value' => 'default',
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_6074076afed15',
			'label' => 'Animation Origin',
			'name' => 'nine3_popup_animation_origin',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_607406f2fed14',
						'operator' => '==',
						'value' => 'slide',
					),
				),
				array(
					array(
						'field' => 'field_607406f2fed14',
						'operator' => '==',
						'value' => 'fade_slide',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'top' => 'Top',
				'left' => 'Left',
				'right' => 'Right',
				'bottom' => 'Bottom',
			),
			'default_value' => 'top',
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'popup',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'side',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

endif;
